version: "3"

services:
  computer:
    image: ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
    env_file: .env
    volumes:
      - .anthropic:/home/computeruse/.anthropic
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    tty: true
    stdin_open: true
